### ISSUE TITLE
Enumerate all BIP32 derivation path patterns for which the Seed Vault should prepopulate public keys

### ISSUE THREAD

**Issue by sdlaver** [solana-mobile/seed-vault-sdk#22]
The reference implementation currently prepopulates keys for:
- m/44'/501'/X'
- m/44'/501'/X'/0'
where 0 <= X < 50, using a SLIP10-Ed25519 key derivation scheme.

The issue exists to enumerate all the standard key derivation path schemes in use, for which the seed vault should prepopulate account public keys. The goal is to ensure that, in practice, a user never sees an authorization popup related to a public key request from a wallet app.

**Comment by Sinishisimus** [comment]
@sdlaver Please find below our input regarding this:
Our recommendation regarding supported derivation paths to be prepopularted on seed auth success is basically the same as it is already recommended:
`m/44'/501'/X' - m/44'/501'/X'/0'`, where 0 <= X < 50, using a SLIP10-Ed25519 key derivation scheme.
If there is a need for additional accounts from other derivation paths, we can later support adding an account from a specific derivation paths and account index, which user will have to authorize, using the existing Seed Vault API:  `requestPublicKey`, https://github.com/solana-mobile/seed-vault-sdk/blob/main/seedvault/src/main/java/com/solanamobile/seedvault/Wallet.java

**Comment by sdlaver** [comment]
No additional default derivation path patterns have been identified. Closing this issue.
